name: CI/CD Pipeline for FirstApp-project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout FirstApp-project
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t usama303/firstapp-project:${{ github.sha }} .

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub Access Token
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push usama303/firstapp-project:${{ github.sha }}

      # Step 7: Tag and push Docker image as latest (if on main branch)
      - name: Tag and push as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag usama303/firstapp-project:${{ github.sha }} usama303/firstapp-project:latest
          docker push usama303/firstapp-project:latest
