name: CI/CD Pipeline for FirstApp-project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Display GitHub Context for Debugging
      - name: Display GitHub Context
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"

      # Checkout the repository with the latest version
      - name: Checkout FirstApp-project
        uses: actions/checkout@v3

      # Set up Node.js with the latest version
      - name: Set up Node.js for FirstApp-project
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies for FirstApp-project
        run: npm install

      # Run tests (if you have any)
      - name: Run tests for FirstApp-project
        run: npm test

      # Build Docker image for FirstApp-project
      - name: Build Docker image
        run: docker build -t ${{ github.repository }}:${{ github.sha }} .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ github.repository }}:${{ github.sha }}

      # Tag and push as latest (if on main branch)
      - name: Tag and push as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:latest
          docker push ${{ github.repository }}:latest
